name: Test

on:
  workflow_dispatch:

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Check Style
        run: cargo fmt --all --check

  test:
    name: Test
    needs: style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: aws-lc-rs tests
        run: cargo test --all --no-default-features --features aws-lc-rs

      - name: default (ring) tests
        run: cargo test --all
